FROM quay.io/centos-bootc/centos-bootc:stream9@sha256:2c164c94b1e8eb4188b3fc1128a2d7c8c0ffcabf7d2ca64d4f5fc0a201d70023

COPY files/ /
COPY scripts/ /tmp/scripts/

RUN chmod +x /tmp/scripts/*.sh /tmp/scripts/base/*.sh && \
  /tmp/scripts/setup.sh && \
  /tmp/scripts/cleanup.sh \
  && \
  bootc container lint
