FROM quay.io/centos-bootc/centos-bootc:stream9

COPY files/ /
COPY scripts/ /tmp/scripts/

RUN chmod +x /tmp/scripts/*.sh /tmp/scripts/base/*.sh && \
  /tmp/scripts/setup.sh && \
  /tmp/scripts/cleanup.sh \
  && \
  bootc container lint
