name: CI

on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: read
  packages: write
  id-token: write

jobs:
  terraform:
    uses: ./.github/workflows/_ci-terraform.yml

  images:
    uses: ./.github/workflows/_ci-images.yml
    with:
      # Push on all main branch pushes and manual workflow_dispatch
      push: ${{( github.event_name == 'push' || github.event_name == 'workflow_dispatch' ) && github.ref == 'refs/heads/main'}}
