name: CI

on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize
      - reopened
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: read

jobs:
  conventional-commits:
    if: ${{ github.event_name }} == 'pull_request_target'
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@0723387faaf9b38adef4775cd42cfd5155ed6017 # v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
