name: CI

on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: read
  packages: write

jobs:
  terraform:
    uses: ./.github/workflows/_ci-terraform.yml

  images:
    uses: ./.github/workflows/_ci-images.yml
    with:
      push: true
