name: CI

on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: read

jobs:
  terraform:
    uses: ./.github/workflows/_ci-terraform.yml
