name: CI

on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read

jobs:
  conventional-commits:
    if: ${{ github.event_name }} == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - name: Validate PR Title
        uses: ytanikin/PRConventionalCommits@1.1.0
        with:
          task_types: '["feat","fix","docs","test","ci","refactor","perf","chore","revert"]'
