name: Release

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write
  packages: write

jobs:
  validate-pr-title:
  runs-on: ubuntu-latest
  steps:
    - name: PR Conventional Commit Validation
      uses: ytanikin/PRConventionalCommits@1.1.0
      with:
        task_types: '["feat","fix","docs","test","ci","refactor","perf","chore","revert"]'

  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@7987652d64b4581673a76e33ad5e98e3dd56832f # v4
        id: release-please
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          config-file: .github/release-please-config.json
          manifest-file: .github/.release-please-manifest.json

      - name: Checkout
        if: ${{ steps.release-please.outputs.releases_created == 'true' }}
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4

      - name: Setup Node.js
        if: ${{ steps.release-please.outputs.releases_created == 'true' }}
        uses: actions/setup-node@1e60f620b9541d16bece96c5465dc8ee9832be0b # v4
        with:
          node-version: "20.x"
          registry-url: "https://npm.pkg.github.com"
          scope: "@immocapital"

      - name: Install Dependencies
        if: ${{ steps.release-please.outputs.releases_created == 'true' }}
        run: yarn install
        env:
          GITHUB_PACKAGES_NPM_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build
        if: ${{ steps.release-please.outputs.releases_created == 'true' }}
        run: yarn build
        working-directory: ./src

      - name: Publish
        if: ${{ steps.release-please.outputs.releases_created == 'true' }}
        run: yarn npm publish
        working-directory: ./src
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_PACKAGES_NPM_TOKEN: ${{ secrets.GITHUB_TOKEN }}
